# <span style="color:green">Numpy</span>

general purpose array processing package.

In [2]:
import numpy as n

In [2]:
x1=n.array([1,2])  # creating an array and storing in variable x1
print(x1)

[1 2]


In [3]:
# to know array dimension
x1.ndim

1

In [4]:
# to know array size
x1.size

2

In [5]:
# to know array data type
x1.dtype

dtype('int64')

### <span style="color:skyblue">Array creation</span>

In [10]:
# create array with range
x2=n.arange(1,5)
print(x2)

[1 2 3 4]


In [12]:
# create array with range and count value
x3=n.arange(1,10,3)
print(x3)

[1 4 7]


In [2]:
# Linspace => number of elements are returned
x4=n.linspace(0,5,10)
print(x4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [37]:
# to create array of zeros which is used in matrix
x5=n.zeros(5)
print(x5)

[0. 0. 0. 0. 0.]


In [40]:
x6=n.zeros((5,2))   # n.zeros((row,column))
print(x6)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [41]:
# to create array of one
x7=n.ones(3)
print(x7)

[1. 1. 1.]


In [43]:
x8=n.ones((3,5))
print(x8)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
# to creare array of random numbers
x9=n.random.randint(1,10)
print(x9)

9


In [47]:
x10=n.random.randint(1,10,5)
print(x10)

[6 4 5 3 9]


In [9]:
# create a array with number of element separated 
x11=n.linspace(0,50,10)
print(x11)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [14]:
# Create an identity matrix.
x12=n.eye(3)
x13=n.eye(3,2)
x14=n.eye(3,2,-1)
print(x12)
print(x13)
print(x14)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[0. 0.]
 [1. 0.]
 [0. 1.]]


In [3]:
x15=n.random.randint(1,20,15)
print(x15)

[ 5  9  6 11 19  1  5  2  4  9 19 17  9  1 16]


### <span style="color:skyblue">Array processing</span>

In [3]:
# to make array in order
x15.sort()

In [5]:
x15

array([ 1,  1,  2,  2,  4,  7,  9, 12, 12, 13, 13, 13, 18, 18, 19])

In [15]:
# to get max element
n.max(x15)

19

In [16]:
# to get min element
n.min(x15)

1

In [6]:
# to check where minimum value is present
x15.argmin()

0

In [7]:
x15

array([ 1,  1,  2,  2,  4,  7,  9, 12, 12, 13, 13, 13, 18, 18, 19])

In [10]:
# to make array in reverse order 
-n.sort(-x11)

array([50.        , 44.44444444, 38.88888889, 33.33333333, 27.77777778,
       22.22222222, 16.66666667, 11.11111111,  5.55555556,  0.        ])

In [28]:
# to check where maximum value is present
x15.argmax()

14

In [17]:
# to find unique values
n.unique(x15)

array([ 1,  2,  4,  7,  9, 12, 13, 18, 19])

In [4]:
x16=n.random.randint(1,10,5)
print(x16)

[4 1 8 6 9]


In [30]:
# to add all the elements in array
n.sum(x16)

42

In [31]:
# to take square root of all elements in array 
n.sqrt(x16)

array([3.        , 2.82842712, 3.        , 2.82842712, 2.82842712])

In [33]:
n.shape(x16)

(5,)

In [5]:
# reshape an array 
x17=x15.reshape(5,3)
print(x17)

[[ 2  4  7]
 [ 8 10 10]
 [11 12 12]
 [14 14 15]
 [15 16 17]]


In [7]:
n.transpose(x17)

array([[13, 18,  9,  4,  7],
       [15, 12, 18, 17, 10],
       [14, 14, 12,  9,  9]])

In [12]:
n.concatenate((x15,x16)) # same dimension.

array([13, 15, 14, 18, 12, 14,  9, 18, 12,  4, 17,  9,  7, 10,  9,  3,  6,
        6,  5,  2])

In [14]:
# split array.  
n.split(x15,3)

[array([13, 15, 14, 18, 12]),
 array([14,  9, 18, 12,  4]),
 array([17,  9,  7, 10,  9])]

In [12]:
n.sum(x16)

26

In [13]:
n.mean(x16)

5.2

In [14]:
# standard deviation
n.std(x16)

2.5612496949731396

In [6]:
x18=n.array([2,5,3,5,8])
n.add(x18,x16)

array([ 6,  6, 11, 11, 17])

In [7]:
n.subtract(x16,x18)

array([ 2, -4,  5,  1,  1])

In [8]:
n.multiply(x16,x18)

array([ 8,  5, 24, 30, 72])

In [9]:
n.ravel(x17)

array([ 2,  4,  7,  8, 10, 10, 11, 12, 12, 14, 14, 15, 15, 16, 17])

In [10]:
x17

array([[ 2,  4,  7],
       [ 8, 10, 10],
       [11, 12, 12],
       [14, 14, 15],
       [15, 16, 17]])

In [11]:
n.dot(x16,x18)

139

In [17]:
x19=n.random.randint(11,50,15)
x19=x19.reshape(5,3)
print(x19)

[[20 33 36]
 [37 40 34]
 [16 44 32]
 [14 37 49]
 [22 16 36]]


In [19]:
n.cross(x19,x17)

array([[  87,  -68,   14],
       [  60,  -98,   50],
       [ 144,  160, -292],
       [-131,  476, -322],
       [-304,  166,  112]])

In [20]:
n.exp(x16)

array([5.45981500e+01, 2.71828183e+00, 2.98095799e+03, 4.03428793e+02,
       8.10308393e+03])

In [21]:
n.log(x16)

array([1.38629436, 0.        , 2.07944154, 1.79175947, 2.19722458])

In [23]:
n.sin(x16)

array([-0.7568025 ,  0.84147098,  0.98935825, -0.2794155 ,  0.41211849])

In [24]:
n.cos(x16)

array([-0.65364362,  0.54030231, -0.14550003,  0.96017029, -0.91113026])

In [25]:
n.tan(x16)


array([ 1.15782128,  1.55740772, -6.79971146, -0.29100619, -0.45231566])

In [29]:
x20=n.array([[1., 2.], [3., 4.]])

In [31]:
n.linalg.inv(x20) # minimum 2-dim

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [32]:
n.linalg.det(x20) # Determinant of a matrix.

-2.0000000000000004

In [33]:
n.linalg.eig(x20) # Eigenvalues and eigenvectors of a square matrix.

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [49]:
x17

array([[ 2,  4,  7],
       [ 8, 10, 10],
       [11, 12, 12],
       [14, 14, 15],
       [15, 16, 17]])

In [58]:
x21=n.array([[2,5,4],[98,75,95],[75,64,26]])
x22=n.array([54,69,78])

In [59]:
n.linalg.solve(x21,x22)

array([-11.65839772,  14.28002091,   1.47917272])

In [62]:
n.linalg.det(x21)

17212.999999999993

In [18]:
n.percentile(x15,42)

5.88

In [13]:
n.sort(x15)

array([ 1,  1,  2,  4,  5,  5,  6,  9,  9,  9, 11, 16, 17, 19, 19])