# <span style="color:green">Numpy</span>

general purpose array processing package.

In [1]:
import numpy as n

In [3]:
x1=n.array([1,2])  # creating an array and storing in variable x1
print(x1)

[1 2]


In [4]:
# to know array dimension
x1.ndim

1

In [5]:
# to know array size
x1.size

2

In [6]:
# to know array data type
x1.dtype

dtype('int64')

### <span style="color:skyblue">Array creation</span>

In [7]:
# create array with range
x2=n.arange(1,5)
print(x2)

[1 2 3 4]


In [8]:
# create array with range and count value
x3=n.arange(1,10,3)
print(x3)

[1 4 7]


In [9]:
# Linspace => number of elements are returned
x4=n.linspace(0,5,10)
print(x4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [10]:
# to create array of zeros which is used in matrix
x5=n.zeros(5)
print(x5)

[0. 0. 0. 0. 0.]


In [11]:
x6=n.zeros((5,2))   # n.zeros((row,column))
print(x6)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
# to create array of one
x7=n.ones(3)
print(x7)

[1. 1. 1.]


In [13]:
x8=n.ones((3,5))
print(x8)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# to creare array of random numbers
x9=n.random.randint(1,10)
print(x9)

9


In [15]:
x10=n.random.randint(1,10,5)
print(x10)

[2 3 4 4 7]


In [16]:
# create a array with number of element separated 
x11=n.linspace(0,50,10)
print(x11)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [2]:
# Create an identity matrix.
x12=n.eye(3)
x13=n.eye(3,2)
x14=n.eye(3,2,-1)
print("x12= ",x12)
print("x13 = ",x13)
print("x14 = ",x14)


x12=  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x13 =  [[1. 0.]
 [0. 1.]
 [0. 0.]]
x14 =  [[0. 0.]
 [1. 0.]
 [0. 1.]]


In [3]:
x15=n.random.randint(1,20,15)
print(x15)

[ 6  1  4  2  5 19 18 19 12  5  9  4  7 10  1]


### <span style="color:skyblue">Array processing</span>

In [4]:
# to make array in order
x15.sort()

In [20]:
x15

array([ 1,  3,  6,  6,  8,  9, 13, 15, 15, 16, 16, 17, 17, 18, 18])

In [21]:
# to get max element
n.max(x15)

18

In [22]:
# to get min element
n.min(x15)

1

In [23]:
# to check where minimum value is present
x15.argmin()

0

In [24]:
x15

array([ 1,  3,  6,  6,  8,  9, 13, 15, 15, 16, 16, 17, 17, 18, 18])

In [25]:
# to make array in reverse order 
-n.sort(-x11)

array([50.        , 44.44444444, 38.88888889, 33.33333333, 27.77777778,
       22.22222222, 16.66666667, 11.11111111,  5.55555556,  0.        ])

In [26]:
# to check where maximum value is present
x15.argmax()

13

In [27]:
# to find unique values
n.unique(x15)

array([ 1,  3,  6,  8,  9, 13, 15, 16, 17, 18])

In [6]:
x16=n.random.randint(1,10,5)
print(x16)

[7 2 4 8 2]


In [29]:
# to add all the elements in array
n.sum(x16)

23

In [30]:
# to take square root of all elements in array 
n.sqrt(x16)

array([1.73205081, 2.82842712, 1.41421356, 2.44948974, 2.        ])

In [31]:
n.shape(x16)

(5,)

In [11]:
# reshape an array 
x17=x15.reshape(5,3)
print(x17)

[[ 1  1  2]
 [ 4  4  5]
 [ 5  6  7]
 [ 9 10 12]
 [18 19 19]]


In [33]:
n.transpose(x17)

array([[ 1,  6, 13, 16, 17],
       [ 3,  8, 15, 16, 18],
       [ 6,  9, 15, 17, 18]])

In [34]:
n.concatenate((x15,x16)) # same dimension.

array([ 1,  3,  6,  6,  8,  9, 13, 15, 15, 16, 16, 17, 17, 18, 18,  3,  8,
        2,  6,  4])

In [35]:
# split array.  
n.split(x15,3)

[array([1, 3, 6, 6, 8]),
 array([ 9, 13, 15, 15, 16]),
 array([16, 17, 17, 18, 18])]

$ mean (\mu) = \frac{sum \ of \ all \ elements }{total \ number \ of \ element}$

In [36]:
n.mean(x16)

4.6

the standard deviation is a measure of how spread out numbers are.<br>
$\sigma = \sqrt{\frac{1}{N}\displaystyle\sum_{i=1}^N (x_i-\mu)^2} $

SD of x16 is <br>

$x_1=(x[0]-\mu)^2$
........$ x_n=(x[n]-\mu)^2$
<br>
$x_i = x_1+x_2+.......+x_n $ <br>
where N= number of element




In [37]:
# standard deviation
n.std(x16)

2.1540659228538015

In [10]:
x18=n.array([2,5,3,5,8])
n.add(x18,x16)

array([ 9,  7,  7, 13, 10])

In [39]:
n.subtract(x16,x18)

array([ 1,  3, -1,  1, -4])

In [40]:
n.multiply(x16,x18)

array([ 6, 40,  6, 30, 32])

In [41]:
n.ravel(x17) # change to 1 dim

array([ 1,  3,  6,  6,  8,  9, 13, 15, 15, 16, 16, 17, 17, 18, 18])

In [42]:
x17

array([[ 1,  3,  6],
       [ 6,  8,  9],
       [13, 15, 15],
       [16, 16, 17],
       [17, 18, 18]])

In [8]:
x19=n.random.randint(11,50,15)
x19=x19.reshape(5,3)
print(x19)

[[17 23 21]
 [30 40 15]
 [27 29 43]
 [16 38 45]
 [40 44 47]]


1. **Dot Product**:

   Given two matrices **A**  and **B**, the dot product (also known as the inner product or scalar product) is calculated as follows:

   $A \cdot B = \sum_{i=1}^{n} A_{ij} \cdot B_{ji} $

   In other words, to compute the dot product, we multiply corresponding elements of the matrices and then sum the results.

   Example:
   $
   A = \begin{bmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   \end{bmatrix}, \quad
   B = \begin{bmatrix} 
   7 & 8 \\
   9 & 10 \\
   11 & 12 \\
   \end{bmatrix}
   $

  $
   A \cdot B = (1 \cdot 7 + 2 \cdot 9 + 3 \cdot 11) + (4 \cdot 8 + 5 \cdot 10 + 6 \cdot 12) = 58 + 139 = 197
  $

2. **Cross Product**:

   The cross product of two matrices is defined only for matrices of dimension $3 \times 1 $ or $ 1 \times 3 $. Given two matrices **A** and **B**, the cross product is calculated as follows:

   $ A \times B = \begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix} \times \begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix} = \begin{bmatrix} a_2 \cdot b_3 - a_3 \cdot b_2 \\ a_3 \cdot b_1 - a_1 \cdot b_3 \\ a_1 \cdot b_2 - a_2 \cdot b_1 \end{bmatrix} $ <br>

   In other words, to compute the cross product, we calculate the determinants of 2x2 matrices formed by taking subsets of the elements of the matrices.

   Example:
  $
   A = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
   B = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}$

   
   $A \times B = \begin{bmatrix} (2 \cdot 6) - (3 \cdot 5) \\ (3 \cdot 4) - (1 \cdot 6) \\ (1 \cdot 5) - (2 \cdot 4) \end{bmatrix} = \begin{bmatrix} -3 \\ 6 \\ -3 \end{bmatrix}
 $

These examples demonstrate how to compute the dot product and cross product of matrices using mathematical notation.

In [15]:
n.dot(x16,x17)

array([143, 157, 186])

In [12]:
n.cross(x19,x17)    

array([[  25,  -13,   -6],
       [ 140,  -90,  -40],
       [ -55,   26,   17],
       [   6,  213, -182],
       [ -57,   86,  -32]])

In [16]:
n.exp(x16)

array([1096.63315843,    7.3890561 ,   54.59815003, 2980.95798704,
          7.3890561 ])

In [17]:
n.log(x16)

array([1.94591015, 0.69314718, 1.38629436, 2.07944154, 0.69314718])

In [18]:
n.sin(x16)

array([ 0.6569866 ,  0.90929743, -0.7568025 ,  0.98935825,  0.90929743])

In [19]:
n.cos(x16)

array([ 0.75390225, -0.41614684, -0.65364362, -0.14550003, -0.41614684])

In [20]:
n.tan(x16)


array([ 0.87144798, -2.18503986,  1.15782128, -6.79971146, -2.18503986])

In [21]:
x20=n.array([[1., 2.], [3., 4.]])

matrix operations in linear algebra.

$2x + 3y = 8$ <br> 
$4x - 2y = 2 $

We can represent this system of equations in matrix form as:

$
\begin{bmatrix} 2 & 3 \\ 4 & -2 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 2 \end{bmatrix}
$

To solve this system of equations, we can use matrix operations. First, let's denote the coefficient matrix as **A** the variable matrix as ***x*** and the constant matrix as **B**

$
A = \begin{bmatrix} 2 & 3 \\ 4 & -2 \end{bmatrix}, \quad X = \begin{bmatrix} x \\ y \end{bmatrix}, \quad B = \begin{bmatrix} 8 \\ 2 \end{bmatrix}
$

To find the solution for \( X \), we can use the formula:

\[
X = A^{-1} B
\]

where $ A^{-1}$ is the inverse of matrix A.

Now, let's perform the matrix operations to find the solution:

1. Calculate the inverse of matrix A:

$
A^{-1} = \frac{1}{\text{det}(A)} \text{adj}(A)
$

2. Calculate the determinant of matrix A:

$
\text{det}(A) = (2 \times -2) - (3 \times 4) = -4 - 12 = -16
$

3. Calculate the adjugate of matrix A:

$
\text{adj}(A) = \begin{bmatrix} -2 & -3 \\ -4 & 2 \end{bmatrix}
$

4. Calculate the inverse of matrix A:

$
A^{-1} = \frac{1}{-16} \begin{bmatrix} -2 & -3 \\ -4 & 2 \end{bmatrix} = \begin{bmatrix} \frac{1}{8} & \frac{3}{16} \\ \frac{1}{4} & -\frac{1}{8} \end{bmatrix}
$

5. Multiply $ A^{-1}$ by matrix  B  to find the solution matrix X:

$
X = A^{-1} B = \begin{bmatrix} \frac{1}{8} & \frac{3}{16} \\ \frac{1}{4} & -\frac{1}{8} \end{bmatrix} \begin{bmatrix} 8 \\ 2 \end{bmatrix} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$

So, the solution to the system of linear equations is \( x = 1 \) and \( y = 2 \).

In [22]:
n.linalg.inv(x20) # minimum 2-dim

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
n.linalg.det(x20) # Determinant of a matrix.

-2.0000000000000004

In [53]:
n.linalg.eig(x20) # Eigenvalues and eigenvectors of a square matrix.

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [54]:
x17

array([[ 1,  3,  6],
       [ 6,  8,  9],
       [13, 15, 15],
       [16, 16, 17],
       [17, 18, 18]])

In [24]:
x21=n.array([[2,5,4],[98,75,95],[75,64,26]])
x22=n.array([54,69,78])

In [25]:
n.linalg.solve(x21,x22)

array([-11.65839772,  14.28002091,   1.47917272])

In [26]:
n.linalg.det(x21)

17212.999999999993

In [27]:
n.percentile(x15,42)

5.0

In [28]:
n.sort(x15)

array([ 1,  1,  2,  4,  4,  5,  5,  6,  7,  9, 10, 12, 18, 19, 19])