# <span style="color:green">Numpy</span>

general purpose array processing package.[Official site](https://numpy.org/)

In [1]:
import numpy as n

In [2]:
print(dir(n))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'arr

In [3]:
n.__version__ # to know the version of numpy lib. 

'2.1.2'

In [26]:
x1=n.array([1,2])  # creating an array of 1d and storing in variable x1
print(x1)

[1 2]


In [27]:
# to know array dimension
x1.ndim

1

In [28]:
# to know array size
x1.size

2

In [29]:
# to know array data type
x1.dtype

dtype('int64')

### <span style="color:skyblue">Array creation</span>

In [30]:
# create array with range
x2=n.arange(1,5)
print(x2)

[1 2 3 4]


In [31]:
# create array with range and count value
x3=n.arange(1,10,3)
print(x3)

[1 4 7]


In [32]:
# Linspace => number of elements are returned
x4=n.linspace(0,5,10)
print(x4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [33]:
# to create array of zeros which is used in matrix
x5=n.zeros(5)
print(x5)

[0. 0. 0. 0. 0.]


In [34]:
x6=n.zeros((5,2))   # n.zeros((row,column))
print(x6)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
x6.ndim

2

In [36]:
# to create array of one
x7=n.ones(3)
print(x7)

[1. 1. 1.]


In [37]:
x7.ndim

1

In [38]:
x8=n.ones((3,5))
print(x8)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
x8.ndim

2

In [40]:
# to creare array of random numbers
x9=n.random.randint(1,10)
print(x9)

9


In [41]:
x10=n.random.randint(1,10,5)
print(x10)

[8 2 4 3 1]


In [42]:
# create a array with number of element separated 
x11=n.linspace(0,50,10)
print(x11)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


### Identity matrix
$
x=\begin{pmatrix}1&0&0\\0&1&0\\0&0&1\end{pmatrix}
$
### Square matrix
Row and column has to be same<br>
$
x=\begin{pmatrix}1&0\\0&1\end{pmatrix}
$
<br>
$
x=\begin{pmatrix}1&0&0&0\\0&1&0&0\\0&0&1&0\\0&0&0&1\end{pmatrix}
$

In [43]:
# Create an identity matrix.
x12=n.eye(3)
x13=n.eye(3,3)
x14=n.eye(4,4,-1)
print("x12= ",x12)
print("x13 = ",x13)
print("x14 = ",x14)


x12=  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x13 =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
x14 =  [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [44]:
x15=n.random.randint(1,20,15)
print(x15)

[ 2  3 19  4 10  8  3 15  6 11  5 19  7  3 13]


### <span style="color:skyblue">Array processing</span>

In [45]:
# to make array in order
x15.sort()

In [46]:
x15

array([ 2,  3,  3,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19, 19])

In [47]:
# to get max element
n.max(x15)

np.int64(19)

In [48]:
# to get min element
n.min(x15)

np.int64(2)

In [49]:
# to check where minimum value is present
x15.argmin()

np.int64(0)

In [50]:
x15

array([ 2,  3,  3,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19, 19])

In [51]:
# to make array in reverse order 
-n.sort(-x11)

array([50.        , 44.44444444, 38.88888889, 33.33333333, 27.77777778,
       22.22222222, 16.66666667, 11.11111111,  5.55555556,  0.        ])

In [52]:
# to check where maximum value is present
x15.argmax()

np.int64(13)

In [53]:
# to find unique values
n.unique(x15)

array([ 2,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19])

In [54]:
x16=n.random.randint(1,10,5)
print(x16)

[5 1 9 5 1]


In [55]:
# to add all the elements in array
n.sum(x16)

np.int64(21)

In [56]:
# to take square root of all elements in array 
n.sqrt(x16)

array([2.23606798, 1.        , 3.        , 2.23606798, 1.        ])

In [57]:
n.shape(x16)

(5,)

In [58]:
# reshape an array 
x17=x15.reshape(5,3)
print(x17)

[[ 2  3  3]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 13]
 [15 19 19]]


In [59]:
n.transpose(x17)

array([[ 2,  3,  6, 10, 15],
       [ 3,  4,  7, 11, 19],
       [ 3,  5,  8, 13, 19]])

In [60]:
n.concatenate((x15,x16)) # same dimension.

array([ 2,  3,  3,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19, 19,  5,  1,
        9,  5,  1])

In [61]:
# split array.  
n.split(x15,3)

[array([2, 3, 3, 3, 4]),
 array([ 5,  6,  7,  8, 10]),
 array([11, 13, 15, 19, 19])]

$ mean (\mu) = \frac{sum \ of \ all \ elements }{total \ number \ of \ element}$

In [62]:
n.mean(x16)

np.float64(4.2)

the standard deviation is a measure of how spread out numbers are.<br>
$\sigma = \sqrt{\frac{1}{N}\displaystyle\sum_{i=1}^N (x_i-\mu)^2} $

SD of x16 is <br>

$x_1=(x[0]-\mu)^2$
........$ x_n=(x[n]-\mu)^2$
<br>
$x_i = x_1+x_2+.......+x_n $ <br>
where N= number of element




In [63]:
# standard deviation
n.std(x16)

np.float64(2.9933259094191533)

In [64]:
x18=n.array([2,5,3,5,8])
n.add(x18,x16)

array([ 7,  6, 12, 10,  9])

In [65]:
n.subtract(x16,x18)

array([ 3, -4,  6,  0, -7])

In [66]:
n.multiply(x16,x18)

array([10,  5, 27, 25,  8])

In [67]:
n.ravel(x17) # change to 1 dim

array([ 2,  3,  3,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19, 19])

In [68]:
x17

array([[ 2,  3,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 13],
       [15, 19, 19]])

In [69]:
x19=n.random.randint(11,50,15)
x19=x19.reshape(5,3)
print(x19)

[[33 26 35]
 [15 38 15]
 [21 34 22]
 [44 17 40]
 [20 19 19]]


1. **Dot Product**:

   Given two matrices **A**  and **B**, the dot product (also known as the inner product or scalar product) is calculated as follows:

   $A \cdot B = \sum_{i=1}^{n} A_{ij} \cdot B_{ji} $

   In other words, to compute the dot product, we multiply corresponding elements of the matrices and then sum the results.

   Example:
   $
   A = \begin{bmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   \end{bmatrix}, \quad
   B = \begin{bmatrix} 
   7 & 8 \\
   9 & 10 \\
   11 & 12 \\
   \end{bmatrix}
   $

  $
   A \cdot B = (1 \cdot 7 + 2 \cdot 9 + 3 \cdot 11) + (4 \cdot 8 + 5 \cdot 10 + 6 \cdot 12) = 58 + 139 = 197
  $

2. **Cross Product**:

   The cross product of two matrices is defined only for matrices of dimension $3 \times 1 $ or $ 1 \times 3 $. Given two matrices **A** and **B**, the cross product is calculated as follows:

   $ A \times B = \begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix} \times \begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix} = \begin{bmatrix} a_2 \cdot b_3 - a_3 \cdot b_2 \\ a_3 \cdot b_1 - a_1 \cdot b_3 \\ a_1 \cdot b_2 - a_2 \cdot b_1 \end{bmatrix} $ <br>

   In other words, to compute the cross product, we calculate the determinants of 2x2 matrices formed by taking subsets of the elements of the matrices.

   Example:
  $
   A = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
   B = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}$

   
   $A \times B = \begin{bmatrix} (2 \cdot 6) - (3 \cdot 5) \\ (3 \cdot 4) - (1 \cdot 6) \\ (1 \cdot 5) - (2 \cdot 4) \end{bmatrix} = \begin{bmatrix} -3 \\ 6 \\ -3 \end{bmatrix}
 $

These examples demonstrate how to compute the dot product and cross product of matrices using mathematical notation.

In [70]:
n.dot(x16,x17)

array([132, 156, 176])

In [71]:
n.cross(x19,x17)    

array([[ -27,  -29,   47],
       [ 130,  -30,  -54],
       [ 118,  -36,  -57],
       [-219, -172,  314],
       [   0,  -95,   95]])

In [72]:
n.exp(x16)

array([1.48413159e+02, 2.71828183e+00, 8.10308393e+03, 1.48413159e+02,
       2.71828183e+00])

In [73]:
n.log(x16)

array([1.60943791, 0.        , 2.19722458, 1.60943791, 0.        ])

In [74]:
n.sin(x16)

array([-0.95892427,  0.84147098,  0.41211849, -0.95892427,  0.84147098])

In [75]:
n.cos(x16)

array([ 0.28366219,  0.54030231, -0.91113026,  0.28366219,  0.54030231])

In [76]:
n.tan(x16)


array([-3.38051501,  1.55740772, -0.45231566, -3.38051501,  1.55740772])

In [77]:
x20=n.array([[1., 2.], [3., 4.]])

matrix operations in linear algebra.

$2x + 3y = 8$ <br> 
$4x - 2y = 2 $

We can represent this system of equations in matrix form as:

$
\begin{bmatrix} 2 & 3 \\ 4 & -2 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 8 \\ 2 \end{bmatrix}
$

To solve this system of equations, we can use matrix operations. First, let's denote the coefficient matrix as **A** the variable matrix as ***x*** and the constant matrix as **B**

$
A = \begin{bmatrix} 2 & 3 \\ 4 & -2 \end{bmatrix}, \quad X = \begin{bmatrix} x \\ y \end{bmatrix}, \quad B = \begin{bmatrix} 8 \\ 2 \end{bmatrix}
$

To find the solution for \( X \), we can use the formula:

\[
X = A^{-1} B
\]

where $ A^{-1}$ is the inverse of matrix A.

Now, let's perform the matrix operations to find the solution:

1. Calculate the inverse of matrix A:

$
A^{-1} = \frac{1}{\text{det}(A)} \text{adj}(A)
$

2. Calculate the determinant of matrix A:

$
\text{det}(A) = (2 \times -2) - (3 \times 4) = -4 - 12 = -16
$

3. Calculate the adjugate of matrix A:

$
\text{adj}(A) = \begin{bmatrix} -2 & -3 \\ -4 & 2 \end{bmatrix}
$

4. Calculate the inverse of matrix A:

$
A^{-1} = \frac{1}{-16} \begin{bmatrix} -2 & -3 \\ -4 & 2 \end{bmatrix} = \begin{bmatrix} \frac{1}{8} & \frac{3}{16} \\ \frac{1}{4} & -\frac{1}{8} \end{bmatrix}
$

5. Multiply $ A^{-1}$ by matrix  B  to find the solution matrix X:

$
X = A^{-1} B = \begin{bmatrix} \frac{1}{8} & \frac{3}{16} \\ \frac{1}{4} & -\frac{1}{8} \end{bmatrix} \begin{bmatrix} 8 \\ 2 \end{bmatrix} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$

So, the solution to the system of linear equations is \( x = 1 \) and \( y = 2 \).

In [78]:
n.linalg.inv(x20) # minimum 2-dim

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [79]:
n.linalg.det(x20) # Determinant of a matrix.

np.float64(-2.0000000000000004)

In [80]:
n.linalg.eig(x20) # Eigenvalues and eigenvectors of a square matrix.

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [81]:
x17

array([[ 2,  3,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 13],
       [15, 19, 19]])

In [82]:
x21=n.array([[2,5,4],[98,75,95],[75,64,26]])
x22=n.array([54,69,78])

In [83]:
n.linalg.solve(x21,x22)

array([-11.65839772,  14.28002091,   1.47917272])

In [84]:
n.linalg.det(x21)

np.float64(17212.999999999993)

In [85]:
n.percentile(x15,42)

np.float64(5.88)

In [86]:
n.sort(x15)

array([ 2,  3,  3,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 19, 19])