### patient detail

In [1]:
import pandas as pd
import numpy as np

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '

In [3]:
x1=np.random.randint(1,50,10)
print("x1= ",x1)

x1=  [46 25 12  8  6 36 43  1 23  8]


In [4]:
p1=np.random.randint(25,100,5)
p2=np.random.randint(25,100,5)
p3=np.random.randint(25,100,5)
p4=np.random.randint(25,100,5)
p5=np.random.randint(25,100,5)

In [5]:
ds1=pd.DataFrame({"person_1":p1,"person_2":p2,"person_3":p3,"person_4":p4,"person_5":p5},index=["tamil","eng","math","science","social"])

In [6]:
ds1

person_1  person_2  person_3  person_4  person_5
tamil          29        83        68        96        78
eng            77        55        65        33        45
math           58        97        65        36        63
science        47        27        68        63        75
social         44        82        68        85        74

In [7]:
ds1["person_2"]

tamil      83
eng        55
math       97
science    27
social     82
Name: person_2, dtype: int64

In [8]:
ds1["person_2"].sum()

344

In [9]:
ds1["person_2"][3]=41

In [10]:
ds1

person_1  person_2  person_3  person_4  person_5
tamil          29        83        68        96        78
eng            77        55        65        33        45
math           58        97        65        36        63
science        47        41        68        63        75
social         44        82        68        85        74

In [11]:
ds1[ds1<35]

person_1  person_2  person_3  person_4  person_5
tamil        29.0       NaN       NaN       NaN       NaN
eng           NaN       NaN       NaN      33.0       NaN
math          NaN       NaN       NaN       NaN       NaN
science       NaN       NaN       NaN       NaN       NaN
social        NaN       NaN       NaN       NaN       NaN

In [12]:
# ds1.idxmax()
ds1[ds1<35]=40

In [13]:
ds1

person_1  person_2  person_3  person_4  person_5
tamil          40        83        68        96        78
eng            77        55        65        40        45
math           58        97        65        36        63
science        47        41        68        63        75
social         44        82        68        85        74

In [14]:
ds1.idxmin()

person_1      tamil
person_2    science
person_3        eng
person_4       math
person_5        eng
dtype: object

In [15]:
me=ds1.mean().T

In [16]:
ds1.loc["mean"]=me

In [17]:
ds1

person_1  person_2  person_3  person_4  person_5
tamil        40.0      83.0      68.0      96.0      78.0
eng          77.0      55.0      65.0      40.0      45.0
math         58.0      97.0      65.0      36.0      63.0
science      47.0      41.0      68.0      63.0      75.0
social       44.0      82.0      68.0      85.0      74.0
mean         53.2      71.6      66.8      64.0      67.0

In [18]:
ds1.rank()

person_1  person_2  person_3  person_4  person_5
tamil         1.0       5.0       5.0       6.0       6.0
eng           6.0       2.0       1.5       2.0       1.0
math          5.0       6.0       1.5       1.0       2.0
science       3.0       1.0       5.0       3.0       5.0
social        2.0       4.0       5.0       5.0       4.0
mean          4.0       3.0       3.0       4.0       3.0

In [19]:
import requests as rq

In [20]:
header={
    "User-Agent":"Mozilla/5.0(x11;Linux x86_64)AppleWebkit/537.36(KHTML,like Gecko)chrome/50.2667.75 Safari/537.36",
    "x_requested-with":"XMLHttp request"
}

In [28]:
wd=rq.get("https://spaceweather.com/",headers=header)

In [29]:
wd

<Response [200]>

In [30]:
wd=pd.read_html(wd.text)

In [31]:
wd

[                                                   0  \
 0                                                NaN   
 1                                                NaN   
 2                                                NaN   
 3  Solar wind  speed: 358.5 km/sec  density: 1.81...   
 
                                1  
 0       All Sky Fireball Network  
 1                            NaN  
 2  Cosmic Rays in the Atmosphere  
 3                            NaN  ,
     0   1   2   3   4
 0 NaN NaN NaN NaN NaN
 1 NaN NaN NaN NaN NaN
 2 NaN NaN NaN NaN NaN
 3 NaN NaN NaN NaN NaN
 4 NaN NaN NaN NaN NaN,
                                                    0  \
 0                                                NaN   
 1                                                NaN   
 2                                                NaN   
 3  Solar wind  speed: 358.5 km/sec  density: 1.81...   
 
                                                    1  \
 0                           All Sky Fireball Net

In [34]:
len(wd)

61

In [35]:
wd[0]

0  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3  Solar wind  speed: 358.5 km/sec  density: 1.81...   

                               1  
0       All Sky Fireball Network  
1                            NaN  
2  Cosmic Rays in the Atmosphere  
3                            NaN

In [36]:
wd[1]

0   1   2   3   4
0 NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN

In [46]:
import numpy as n
x16=n.random.randint(1,10,5)

In [47]:
x16

array([4, 3, 9, 6, 6])

In [48]:
n.sum(x16)

28

In [49]:
n.sqrt(x16)

array([2.        , 1.73205081, 3.        , 2.44948974, 2.44948974])

In [50]:
n.shape(x16)

(5,)

In [51]:
x12=n.random.randint(1,10,5)

In [52]:
x12

array([3, 2, 2, 7, 9])

In [53]:
x12.sort()

In [54]:
x12

array([2, 2, 3, 7, 9])

In [55]:
n.max(x12)

9

In [56]:
n.min(x12)

2

In [57]:
x12.argmin()

0

In [58]:
x12.argmax()

4

In [59]:
n.unique(x12)

array([2, 3, 7, 9])

In [64]:
print(x12)

[2 2 3 7 9]


In [66]:
n.log(x16)

array([1.38629436, 1.09861229, 2.19722458, 1.79175947, 1.79175947])

In [67]:
n.sin(x16)

array([-0.7568025 ,  0.14112001,  0.41211849, -0.2794155 , -0.2794155 ])

In [68]:
n.cos(x16)

array([-0.65364362, -0.9899925 , -0.91113026,  0.96017029,  0.96017029])

In [69]:
n.tan(16)

0.3006322420239034

In [71]:
import numpy as n

In [73]:
x1=n.array([1,2])
print(x1)

[1 2]


In [75]:
x1.size

2

In [76]:
x1.dtype

dtype('int64')

In [79]:
x2=n.arange(1,5)
print(x2)

[1 2 3 4]


In [101]:
x3=n.arange(1,10,2)
print(x3)

[1 3 5 7 9]


In [88]:
x4=n.linspace(0,5,10)
print(x4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [92]:
x5=n.zeros(5)
print(x5)

[0. 0. 0. 0. 0.]


In [95]:
x6=n.zeros((5,6))
print(x6)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [96]:
x7=n.ones(3)
print(x7)

[1. 1. 1.]


In [97]:
x8=n.ones((3,5))
print(x8)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [98]:
x9=n.random.randint(1,10)
print(x9)

7


In [99]:
x10=n.random.randint(1,10,5)
print(x10)

[8 8 2 2 7]


In [100]:
x11=n.linspace(0,50,10)
print(x11)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
